(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2024-08-30 12:03:56
  From session:  30082024_myTest
  Captured on:  2024-08-30 12:01:58
  From server:  IB-171
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

Click "image0004"
Click "image0005"
TypeText Param1
Click "image0006"
Click "chromehttpsmy359835ssocrmondem"
Drag "chromehttjsmy359835ssoermondem"
Drop "image0007"
TypeText Backspace,Backspace,Return
TypeText Param2,Return
Click "image0008"
MoveTo "image0009"
Click text:Param3
MoveTo text:Param4
Click "image0008"
MoveTo "image0009"
ScrollWheelDown 0.8
MoveTo "image0010"
ScrollWheelDown 0.1
MoveTo "image0011"
ScrollWheelDown 0.1
MoveTo "image0012"
ScrollWheelDown 0.1
MoveTo "image0013"
ScrollWheelUp 1.4
ScrollWheelDown 0.0
Click "image0014"
Click "ReplacementorupgradeproductInf"
Click "image0015"
Click "NetworkAnalyzersImpedanceAnaly"
Click "ONeedtechnicalsupport"
Click "image0016"
TypeText Param5
Click "Yeskeepmeupdatedonthelatestpro"
MoveTo "image0017"
ScrollWheelDown 1.6
MoveTo "image0018"
ScrollWheelDown 2.0
Drag "image0019"
Drop "image0020"
MoveTo "image0021"
ScrollWheelDown 0.4
MoveTo "GfflX"
ScrollWheelDown 0.1
Click "image0022"
Click "image0023"
Click "image0024"
Click "image0025"
Click "Lookingtocreateapageforabusine"
Click "Lookingtocreateapageforabusine_0001"