
TestCaseCreator "Phase2.xml","XMLtrail.xlsx"
TestCaseCreator "KeySight_testcases-testcase-report-Fri Mar 18 2022.xml"


TestCaseCreator "KeySight_testcases-testcase-report-Wed Mar 16 2022.xml","XMLtrail.xlsx"


to handle TestCaseCreator
	params XMLFile,ExcelFile 
	set MyExcelFile to Workbook(ResourcePath(ExcelFile)) 
	set Sheet1 to worksheet(MyExcelFile,1)
	
	put "Subject" into Cell(Sheet1,[1,1])
	put "TestCase Name" into Cell(Sheet1,[1,2])
	put "Type" into Cell(Sheet1,[1,3])
	put "Description" into Cell(Sheet1,[1,4])
	put "Step Name" into Cell(Sheet1,[1,5])
	put "Description (Design Steps)" into Cell(Sheet1,[1,6])
	put "Expected Result (Design Steps)" into Cell(Sheet1,[1,7])
	put "Approval Status" into Cell(Sheet1,[1,8])
	put "GxP Flag" into Cell(Sheet1,[1,9])
	put "Test Script Phase" into Cell(Sheet1,[1,10])

	put file ResourcePath(XMLFile) as a tree into XMLTree
	put all nodes "*/root" of XMLTree into temp
	set Global ActionsCount to 0
	repeat the number of items of temp times
		put item repeatIndex() of temp into temp2
		put the text of node "/root/testcaseName" of temp2 into item repeatIndex() of Global TestNameList
		put the text of node "/root/testcaseDescription" of temp2 into item repeatIndex() of Global TestDescriptionList
		put the text of node "/root/testcase" of temp2 into RawTestCaseData
		repeat the number of items of RawTestCaseData times
			put  item repeatIndex() of RawTestCaseData into RawItem
			if RawItem contains "::"
				split RawItem by "::"
				if item 2 of RawItem contains "Param"
					put item 2 of RawItem into RawItemTemp
					split RawItemTemp by "Param"
					if item 1 of RawItemTemp contains "\" then 
						delete every occurence of "\" in item 1 of RawItemTemp
					end if 
					if item 1 of RawItemTemp contains quote then 
						delete every occurence of quote in item 1 of RawItemTemp
					end if 
					if last character of  item 1 of RawItemTemp is space then 
						delete last character of  item 1 of RawItemTemp
					end if
					put item 1 of RawItemTemp into item repeatIndex() of  Global Action
				else 
					if item 2 of RawItem contains "\" then 
						delete every occurence of "\" in item 2 of RawItem
					end if 
					if item 2 of RawItem contains quote then 
						delete every occurence of quote in item 2 of RawItem
					end if 
					if last character of item 2 of RawItem is space then 
						delete last character of  item 2 of RawItem
					end if
					put item 2 of RawItem into item repeatIndex() of Global Action
				end if 
			else 
				split RawItem by space
				if last character of item 2 of RawItem is space then
					delete last character of item 2 of RawItem
				end if 
				if item 2 of RawItem contains "\" then  
					delete every occurrence of "\" in item 2 of RawItem 
				end if 
				if item 2 of RawItem contains quote then 
					delete every occurence of quote in item 2 of RawItem
				end if 
				put item 2 of RwaItem into item repeatIndex() of Global Action
			end if 
		end repeat 
		Log Global Action
		put the number of items of Global Action into Count
		put Global ActionsCount into item repeatIndex() of Global ActionListCount
		repeat Count times
			put item repeatIndex() of Global Action into Cell(Sheet1,[repeatIndex()+Global ActionsCount+1,5])
		end repeat
		put (Global ActionsCount + Count) into Global ActionsCount 
	end repeat 
	put the number of items of Global TestDescriptionList into DescriptionCount
	repeat (DescriptionCount+1) times
		//TestCase name
		put item repeatIndex() of Global TestNameList  into Cell(Sheet1,[(item repeatIndex() of Global ActionListCount + 2) ,2])
		//Test description
		put item repeatIndex() of Global TestDescriptionList  into Cell(Sheet1,[(item repeatIndex() of Global ActionListCount + 2) ,4])
		//subject value in Templete
		put "TestCaseFolderpath" into Cell(Sheet1,[(item repeatIndex() of Global ActionListCount + 2) ,1])
		//Type value in Templete
		put "VAPI-XP-TEST" into Cell(Sheet1,[(item repeatIndex() of Global ActionListCount + 2) ,3])
		//Approval Status in Templete
		put "VYerekar" into Cell(Sheet1,[(item repeatIndex() of Global ActionListCount + 2) ,8])
		//GxP Flag in Templete
		put "Non-GxP" into Cell(Sheet1,[(item repeatIndex() of Global ActionListCount + 2) ,9])
		//Test Script Phase in Templete
		put "SIT/IT" into Cell(Sheet1,[(item repeatIndex() of Global ActionListCount + 2) ,10])
	end repeat 
	
end TestCaseCreator