put GetModelTestRuns() into APIResponse
put APIResponse.responseBody into JSONResponse
put JSONValue(JSONResponse) into ResponseValue
log ResponseValue
log the number of items of ResponseValue
log item 2 of ResponseValue


---------------------
put GetModelTestRuns().responseBody into response
//log response

put JSONValue(response) into jsonResponse
repeat with each item respItems of jsonResponse
	//log respItems
	if repeatIndex() is 2 then
		Put "Item 2 Response"
		log respItems
		put JSONFormat(respItems) into jsonRespnew
		log jsonRespnew
		put JSONValue(jsonRespnew) into jsonValueResp
		log jsonValueResp
		put jsonValueResp.testconfigtask into jsonConfigTasks
		Put "JSON Config Tasks" & jsonConfigTasks
		repeat with each item testConfig of jsonConfigTasks
			log testConfig.locked_suts
		end repeat
	end if
end repeat
