(*** Autosnippet script "LoginPage" generated 2018-07-23 by Carrie. Keep this comment for use with Eggplant AI. ***)
(* Already generated snippets can be edited in the script below *)
(* To customize the snippet generation templates, affecting snippets generated in the future,
go to Eggplant > Preferences... > Script > General > Customize *)


(* Autosnippets for Checkpoint "EggplantLogo" *)

to handle EggplantLogo_Validate duration
	if duration is not a number then set duration to 8
	WaitFor duration, imageName:"EggplantLogo"
end EggplantLogo_Validate

to handle EggplantLogo_IsFound duration
	if duration is not a number then set duration to 8
	return imageFound(imageName:"EggplantLogo", waitFor:duration)
end EggplantLogo_IsFound

-----------------------------------


(* Autosnippets for Field "Username" *)

to handle Username_EnterText theValue, terminator
	// Assumes the hot spot has been set over the text field
	// and that the field is already empty.
	
	// Click the location of the hot spot.
	//Click imageName:"Username", waitFor:8
	//Type theValue and optional terminator (such as 'return' or 'tab') into the field.
	TypeText theValue, terminator
end Username_EnterText

to handle Username_ReadText
	// Assumes the hot spot has been set over the text field.
	
	// Use OCR to read the text around that hot spot point.
	set theText to readText(imageLocation(imageName:"Username"))
	// Any additional cleanup of the text could be done here before returning the value, such as:
	// set theText to trim(theText) -- remove leading/trailing whitespace
	return theText
end Username_ReadText

-----------------------------------


(* Autosnippets for Field "Password" *)

to handle Password_EnterText theValue, terminator
	// Assumes the hot spot has been set over the text field
	// and that the field is already empty.
	
	// Click the location of the hot spot.
	Click imageName:"Password", waitFor:8
	//Type theValue and optional terminator (such as 'return' or 'tab') into the field.
	TypeText theValue, terminator
end Password_EnterText

to handle Password_ReadText
	// Assumes the hot spot has been set over the text field.
	
	// Use OCR to read the text around that hot spot point.
	set theText to readText(imageLocation(imageName:"Password"))
	// Any additional cleanup of the text could be done here before returning the value, such as:
	// set theText to trim(theText) -- remove leading/trailing whitespace
	return theText
end Password_ReadText

-----------------------------------


(* Autosnippets for Button "Login" *)

to handle Login_Click
	Utilities.DismissKeyboard
	Click imageName:"Login", waitFor:8
end Login_Click

-----------------------------------


(*** End of Autosnippet script LoginPage.script ***)

