DoubleClick [68,47]
TypeText "http://docs.eggplantsoftware.com/ePF/SenseTalk/stk-ocr-text-reading-functions.htm#readtable-function",returnKey
create file "C:\Users\DurgaPrasad-IB\Surath\tabledata.csv"
put "C:\Users\DurgaPrasad-IB\Surath\tabledata.csv" into myfile
set global col to empty
set topleft to ImageLocation("TB")
set bottomright to ImageLocation("BB")
put readtable(topleft,bottomright) into table1
repeat the number of items of table1
	put item 1 of item repeatIndex() of table1 into item repeatIndex() of global col's work
	put item 2 of item repeatIndex() of table1 into item repeatIndex() of global col's topic
	put item 3 of item repeatIndex() of table1 into item repeatIndex() of global col's assign
end repeat
open file myfile
write  global col to file myfile
close file myfile

///////////////////////////////////////////////

DoubleClick [68,47]
TypeText "http://docs.eggplantsoftware.com/ePF/SenseTalk/stk-ocr-text-reading-functions.htm#readtable-function",returnKey
create file "C:\Users\DurgaPrasad-IB\Surath\tabledata.csv"
put "C:\Users\DurgaPrasad-IB\Surath\tabledata.csv" into myfile
set topleft to ImageLocation("TB")
set bottomright to ImageLocation("BB")
put readtable(topleft,bottomright) into table1
repeat the number of items of table1
	open file myfile
	put item 1 of item repeatIndex() of table1 into item 1 of  line repeatIndex() of  file myfile
	//Log item 1 of item repeatIndex() of table1
	put item 2 of item repeatIndex() of table1 into  item 2 of line repeatIndex() of  file myfile
	//Log item 2 of item repeatIndex() of table1
	put item 3 of item repeatIndex() of table1 into  item 3 of line repeatIndex() of  file myfile
	//Log item 3 of item repeatIndex() of table1
	close file myfile
end repeat



///////////////////////////////////////////
DoubleClick [68,47]
TypeText"http://demo.guru99.com/test/web-table-element.php",returnkey,waitfor:5 
set tab1 to imageLocation("TabTop")
set tab2 to imageLocation("TabBottom")
//put readtable(tab1,tab2) into tab
//log tab
put ReadText(tab1,tab2) into tab
log tab

//////////////////////////////////////

DoubleClick [68,47]
TypeText"http://demo.guru99.com/test/web-table-element.php",returnkey,waitfor:5 
set tab1 to imageLocation(Text:"Company")
log tab1
set tab2 to imageLocation(Text:"+ 5.2")
log tab2

put ReadText(tab1,tab2) into tab
log tab
put readtable(tab1,tab2) into tab
log tab

//////////////////////////////////

set SearchRectangle to [[459,270],[1077,1078]] 
Log readtable(Text:"Company")

