put FindElement(WebXPath:"//*[@id='getting-startedepf-getting-started-eggplant-functionalmd']/a[1]") into myElement
put +

ExecuteJavaScript "scroll(0,200)" 


put WebDriver() // Returns information about the active WebDriver connection: <WebDriverConnection with Name:"iphone6plus", PlatformName:"iOS", Host:"localhost", BundleID:"com.testplant.YetAnotherSampleApp">


set driver to WebDriver(host:"localhost", port: "5000", platformName: "andriod", appPackage: "com.android.chrome")
log driver

set driver to WebDriver(host: "localhost", port: "5000", platformName: "Android", appPackage:"com.google.android.apps.maps", appActivity:"com.google.android.maps.MapsActivity", automationName:"UIAutomator2")
log driver

ExecuteJavaScript {{
function logMessage() {
  console.log("This is a repeated message.");
}
logMessage;
}}