
//4 0002133058


To handle randomGen
	put the abbrev time into time_t
	delete every occurrence of  ":" in time_t
	put the date into date_t
	split date_t by "/"
	//log item 1 of date_t& item 2 of date_t&time_t
	return item 1 of date_t& item 2 of date_t&time_t
End randomGen

//put randomGen()

//the value of 
//the text of 
//INSPECTIONLOT

InspectionLotReader "XMl Teamplate01.xml"

to handle InspectionLotReader
	params XMLFile
	put file ResourcePath(XMLFile) as a tree into XMLTree
	//put all nodes "*/Rowset/Row/INSPECTIONLOT" of XMLTree  into  temp
	
	put all nodes "*/Rowset/Row/*" of XMLTree  into  temp
	//log temp as tree
	put  the number of items of temp into count
	repeat with each item  of all nodes "*/Rowset/Row/*" of  XMLTree
		//log it
		//log the text of  node "/INSPECTIONLOT" of it
		//log  the text of  node "*/Rowset/Row/INSPECTIONLOT" of XMLTree
		put 3 into  the text of  node "*/INSPECTIONLOT" of it
		//log node "*/Rowset/Row/INSPECTIONLOT" of it
		//put 7 into node "*/Rowset/Row/INSPECTIONLOT" of it 
		log it
	end repeat
	//log XMLTree
	//repeat count times
	//log the text of item repeatIndex() of all nodes "*/Rowset/Row/INSPECTIONLOT" of XMLTree 
	//log  the text of   item repeatIndex() of every  node "*/Rowset/Row/INSPECTIONLOT" of XMLTree 
	//log the text of item 1 of all nodes "*/Rowset/Row/INSPECTIONLOT" of XMLTree 
	//log the text of item 1 of the value of all nodes "*/Rowset/Row/INSPECTIONLOT" of XMLTree 
	//log the value of item 1 of all nodes "*/Rowset/Row/INSPECTIONLOT" of XMLTree 
	//log the text of item 1 of all nodes "*/Rowset/Row/INSPECTIONLOT" of XMLTree 
	
	//log the text of item 1 of all nodes "*/Rowset/Row/*" of XMLTree 
	//log  the text of item 2 of all nodes "*/Rowset/Row/*" of XMLTree
	
	//log  the text of node  "*/Rowset/Row/*" of XMLTree
	
	//log  node  "*/Rowset/Row/INSPECTIONLOT" of XMLTree
	//log item 2 of XMLTree
	//log  the text of item 2 of  node 1 of "*/Rowset/Row/*" of XMLTree
	
	//log item 2 of all nodes "*/Rowset/Row/*" of XMLTree 
	//log  node "*/Rowset/Row/INSPECTIONLOT" of XMLTree 
	
	//log  item 2 of XMLTree of item 1 of node "*/Rowset/Row/" of XMLTree 
	//log item 4 of item 1 of node "*/Rowset/Row" of XMLTree 
	//log item 4 of item 1 of "*/Rowset/Row/" of node "*/Rowset/Row/*" of XMLTree 
	//put 7 as value into the text of item 1 of all nodes "*/Rowset/Row/INSPECTIONLOT" of XMLTree 
	//log item 13 of node "*/Rowset/Row/INSPECTIONLOT" of XMLTree 
	//put 7 into item 1 of node "*/Rowset/Row/INSPECTIONLOT" of XMLTree 
	//put << <INSPECTIONLOT> >> 7 << <INSPECTIONLOT/> >> into item repeatIndex() of   node "*/Rowset/Row/" of XMLTree 
	//insert << <customer name="Jane Doe"/> >>
	//end repeat
	
end InspectionLotReader




